---
name: Make

on:
  schedule:
    - cron: '0 0 1 * *'
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  make:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build on Unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          bash '.github/workflows/make.sh'
